name: perf-dev
channels:
  - conda-forge
  - numba
dependencies:
  - python=3.7
  - coiled=0.0.37
  - pip=21.0.1
  - compilers=1.1.3
  - Cython=0.29.22
  - stacktrace=0.1dev0
  - uvloop=0.15.2
  - ipython=7.21.0
  - jupyterlab=3.0.11
  - jupyter-server-proxy=3.0.2
  - viztracer=0.12.2
  - bokeh=2.3.0
  - graphviz=2.40.1
  - matplotlib=3.3.4
  - seaborn=0.11.1
  - numpy=1.20.1
  - pandas=1.2.3
  - xarray=0.17.0
  - pip:
    - gprof2dot==2021.2.21
    - git+https://github.com/dask/distributed.git@main --install-option="--with-cython=profile"
    - git+https://github.com/dask/dask.git@main
variables:
  DASK_CONFIG: dask.yaml